version: "3.1"
services:
  api-age-group:
    build:
      context: ./api-age-group
    ports:
      - "8000:8000"
    volumes:
      - ./api-age-group/app:/app
    command: sh -c "uvicorn main:app --host 0.0.0.0 --reload"
    depends_on:
      - mongodb
    env_file:
      - ./.env
  api-enrollment:
    build:
      context: ./api-enrollment
    ports:
      - "8001:8000"
    volumes:
      - ./api-enrollment/app:/app
    command: sh -c "uvicorn main:app --host 0.0.0.0 --reload"
    depends_on:
      - mongodb
      - rabbitmq
    env_file:
      - ./.env
  processor:
    build:
      context: ./processor
    command: sh -c "python main.py"
    depends_on:
      - mongodb
      - rabbitmq
      - api-enrollment
    env_file:
      - ./.env
  mongodb:
    image: mongo:latest
    restart: always
    env_file:
      - ./.env
    ports:
      - "27017:27017"
  rabbitmq:
    image: "rabbitmq:3-management"
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - "./data/rabbitmq:/var/lib/rabbitmq"
